### ISSUE TITLE
Assoc conversion causes unintended value change

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/forms#65]
This is  a **bug**.

### Prerequisites
yes

### Description

The change in `readTemplate` introduced in https://github.com/laravel-enso/FormBuilder/commit/3726fa139a180b9914755b4eea1f5dbec8a09228#diff-2e39d0f5a27f1453796dcb9b88bc1e21R182 to convert everything to an assoc array instead of using stdClasses is causing an unintended conversion from (default) value `{}` to `[]`.

This is causing issues for custom elements being saved under a `json` (array) property (lost data).
Was there a good reason to change this to use `assoc`? Or just didn't realize the limitations this could introduce?

### Steps to Reproduce
1. Have a (custom) form element with default value `{}` defined in the .json template
2. When trying to add a (tested with) numeric key to it, it creates an array of length x instead

### Expected behavior

`{}` in the json template to remain `{}` in the json returned to frontend

### Actual behavior

`{}` being converted to `[]` because of the change introduced in https://github.com/laravel-enso/FormBuilder/commit/3726fa139a180b9914755b4eea1f5dbec8a09228#diff-2e39d0f5a27f1453796dcb9b88bc1e21R182

### Workaround

Define the value in the form `create()` function, f.e.: `$this->form->value('customField', new \stdClass());`

**Comment by jlsjonas** [comment]
Note that the workaround only works for create, if the db-stored value is `{}` it still converts it to an array

**Comment by aocneanu** [comment]
You shoud be able to do the same in edit, `value('custom', $model->custom)`.

Could you give me more details about the context where you would need that? Maybe I can find a solution.

**Comment by jlsjonas** [comment]
>You should be able to do the same in edit

Realized that after commenting, however this still looks like unexpected behaviour (and is connected to the change to use `assoc` combined with the `obj` helper)

context: storing some metadata about a model directly on the model (using json) the way the model is defined & used requires it to be an assoc array (i.e. object, in js terms)... on the front-end which the parse-assoc in the BE is preventing in case of an empty object (as an empty object & array look exactly the same in php after an assoc parse)

**Comment by aocneanu** [comment]
I need to look thoroughly in forms / tables and other places where we use the Obj container and see what it takes to replace it with Laravel's collection. It seems that there are too many side effects.

**Comment by aocneanu** [comment]
@jlsjonas could you test now and see if the problem is still present?

**Comment by jlsjonas** [comment]
I'll be upgrading our stack this week & let you know

**Comment by aocneanu** [comment]
reopen if still exists
