### ISSUE TITLE
Edit Form Select Field not showing current value

### ISSUE THREAD

**Issue by bytebuddha** [laravel-enso/forms#68]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When using a non multiple select form field with a `label` attribute the field value is not set to the correct value, it shows as null.

Example form field json
```
          {
            "label": "Owner",
            "name": "owner",
            "value": null,
            "meta": {
              "trackBy": "selectId",
              "label": "label",
              "type": "select",
              "source": "devices.owners"
            }
          }
```

Example Form response
```
          {
            "label": "Owner",
            "name": "owner",
            "value": null,
            "meta": {
              "trackBy": "selectId",
              "label": "label",
              "type": "select",
              "source": "devices.owners"
            }
          }
```
### Steps to Reproduce
1. Create a form with a select element that is not multiple and has the label attribute set to something other than name.
2. Use the Form to Edit the record and its current value will not be set automatically like a Field without the 'label' attribute will be.

### Expected behavior

To auto fill like all the other form fields do.
### Actual behavior

Appears to return null instead of current value.

I think this is because of this line
https://github.com/laravel-enso/forms/blob/fa9b8644529ccd87f4b8596172fef9a85ef05b83/src/app/Services/Builder.php#L56

I think it should be this instead.
```
: $this->model->{$field->get('label') ?? $field->get('name')}
```

**Comment by aocneanu** [comment]
That line is correct. It's not really clear for me what you're attempting to achieve.

But try the following:

- edit `MenuForm.php` and add to the `parent_id` query the `icon` attribute:

`Menu::isParent()->get(['id', 'name', 'icon']`

- edit `menu.json` form template and add to the `parent_id` field's meta `"label": "icon"`

Now go to the menu table and edit a menu. You should see the `icon` instead of name, and that's seems to me exactly what you're describing above, at least the reproduction steps.

Regarding the actual problem, please provide more context.

**Comment by bytebuddha** [comment]
Ok my app is for support ticket management at a repair shop. I'm trying to achieve a select input in a form that can select from multiple api endpoints. The two main one's i would like and am testing with are `administration.people.options` & `administration.companies.options`.  I have built an options route following the original implementation that works as expected

**Comment by aocneanu** [comment]
So you figured it out?

**Comment by bytebuddha** [comment]
No sorry, I was in the middle of my reply and i hit the wrong button. And waited to finish to reopen

**Comment by aocneanu** [comment]
```json
{
    "label": "Owner",
    "name": "owner",
    "value": null,
    "meta": {
        "label": "label",
        "trackBy": "selectId",
        "type": "select",
        "source": "http://localhost:8000/api/tickets/owners",
        "placeholder": "Choose"
    }
},
```

For this to work (autopopulate on edit) when you are calling `$form->edit($model)` you have to make sure that `$model->owner` would exist and return the desired value. If the column is `owner_id` in your database then you have to set the proper `name` attribute in the field declaration.

`trackBy` is used in FE so the select can figure out how to match the `v-model` with the list of options.

**Comment by bytebuddha** [comment]
Thank you so much! I was able to solve this by simple adding this to my Model
```php
    protected $appends = ['owner'];

    public function getOwnerAttribute() {
      $cfg = config('vstekscrm.devices.ownerSelect.ownableModels');
      return $cfg[$this->owner_type]['slug'].':'.$this->owner_id;
    }
```
