### ISSUE TITLE
Put field value to created form in custom method

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/forms#69]
Feature request

### Prerequisites
* [+] Are you running the latest version?
* [+] Are you reporting to the correct repository?
* [+] Did you check the documentation?
* [+] Did you perform a cursory search?

### Description
I have create a custom filed, and custom method.
I have get values from form in my custom method by this one this.$refs.ensoForm.formData()
How can I put value to my form field using $refs or is some other method or function?

**Comment by aocneanu** [comment]
If you want to set the value from the FE you can do `this.$refs.ensoForm.field('yourField').value = 'someting'`.

But you should try to set everything from the BE when possible.

**Comment by VadimsTalapins** [comment]
Thank. I make dynamic fields and at the moment of sending I complete them in json, and write it in one field.

**Comment by aocneanu** [comment]
Ok. Can we close this issue if it's solved?

**Comment by VadimsTalapins** [comment]
Yes, thank you very much for your help.
