### ISSUE TITLE
Able to enable/disable tabs in form

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/forms#70]
This is  a **feature request**.

### Prerequisites
* [ v] Are you running the latest version?
* [ v] Are you reporting to the correct repository?
* [ v] Did you check the documentation?
* [v ] Did you perform a cursory search?

### Description
It would be nice if we could enable/disable tabs dynamically and/or by permission. Some times we maybe need to disable a tab to some users that not have permission to see or edit some information.

### Expected behavior
enable/disable tabs dynamically and/or by permission

### Actual behavior
we could not enable/disable tabs dynamically and/or by permission

Is possible to use scope to enable/disable tabs by custom script?
the documentation of the Tabs have a method to disable, but the documentation of the forms don't mention it. I have a case that a role user will not be able to see a tab that has information about bank accounts, just the admins and the role named "Financier"

**Comment by aocneanu** [comment]
You can now use `$form->hideSection($fields)` on the BE where `$fields` can be a field name or an array of fields names. The helper will hide all the fields in the section(s) that have the provided field(s).

The FE was updated and now hides tabs with empty sections.

You can add your restricting logic in the BE's form object:

```php
if ($user->cannot('access-route', $routeName) {
    $form->hideSection('privateSection');
}
```

or use the FE to hide individual fields `$refs.form.field('field').meta.hidden = true`.

**Comment by aocneanu** [comment]
Ah @boing6000, I would really appreciate a PR to the docs from you with the above ;)

**Comment by boing6000** [comment]
Hi, thanks,

I have added to EnsoForm.vue this 2 methods:

           hideTab(tab){
                return this.ready
                    ? this.sections(tab).forEach(section => section.fields.forEach(field => field.meta.hidden = true))
                    : null;
            },
            showTab(tab){
                return this.ready
                    ? this.sections(tab).forEach(section => section.fields.forEach(field => field.meta.hidden = false))
                    : null;
            }

and in the CoreForm.vue before the render function:

watch:{
        'state.data.sections': {
            handler: function(val){
                this.$forceUpdate();
            },
            deep: true
        }
    },

With this i could show/hide tabs dynamically in a switch like below:

    showTab1() {
               return event 
                          ? this.$refs.form.showTab('tab1')
                          :  this.$refs.form.hideTab('tab2');
    }

**Comment by boing6000** [comment]
i have to do the trick to this.$forceUpdate() because the keep-alive of the tab not update the hidden or disabled meta change in the field using what you suggested "$refs.form.field('field').meta.hidden = true"

**Comment by boing6000** [comment]
i can do a PR in @enso-ui/forms with this change if you want.

**Comment by aocneanu** [comment]
Sure.

You should place the methods in CoreForm and cascade them in VueForm and then EnsoForm (just like the other methods that are cascaded).

**Comment by boing6000** [comment]
ok, i did cascade in VueForm and EnsoForm from CoreForm and made a PR in enso-ui/forms
