### ISSUE TITLE
Overriding user form user.json - more flexibility

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/forms#76]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Let's say i wanted to add a new user attribute like "type". Added DB and model support, and where it comes to Form builder or even table builder, in order to override the Enso user.json I need to use the local binding for `lbdash/vendor/laravel-enso/core/src/app/Forms/Builders/UserForm.php` to `\app\Forms\Builders\Models\UserForm.php`. But, if I do this, the typehint of second parameter "UserForm" in 

`php
class Edit extends Controller
{
    public function __invoke(User $user, UserForm $userform)
    {
`

Will return an exception because it expects the Enso instance, not my local. If I go further, and try to override also the Edit Controller with my own, it goes even weirder with null data being returned in the __invoke... and here i stopped investigating since this seems very easy to fix if we're allowed to change the `private const TemplatePath = __DIR__.'/../../Templates/Models/user.json';` (protected?)

Maybe i'm not thinking this through, or there is another way to solve this but what I know, is that I change the Enso UserForm "use" statement with the path to my local one (override) it will work.

Thank you!

**Comment by aocneanu** [comment]
To get an Enso instance make sure the local classes extend the Enso ones.

**Comment by robbykrlos** [comment]
That was easy, thank you
