### ISSUE TITLE
disable form keeping changes

### ISSUE THREAD

**Issue by jaminjava** [laravel-enso/forms#81]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

How can I disabled the feature that keeps changes in forms. for example if we write anything in form and thn submit it or refresh pages, it always keeps data in same state, and then we can revert changes or clean for by using "change button on form". How can I disable this feature for whole project???

**Comment by aocneanu** [comment]
Right now you can only disable state individually for each form, from the front-end.

You can to that by passing "disable-state" on the component.

I believe it could be a good addition to add a global flag in the config, as well as individual flags in the json template.
