### ISSUE TITLE
Customize buttons/actions between Create and Edit Forms

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/forms#92]
This is  a **eature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Hi, I need to have different buttons visible for Create/Edit forms for a specific resource. For example on Create I want to have only back and Save and for Edit I want to have also the Delete button. 
Since the configurations are saved in the same .json file, for example product.json, how can I differentiate between them? Is there an easy way that I did not see?
Example:
Edit: "actions": ["store", "destroy", "back"],
Create: "actions": "actions": ["store", "back"],

**Comment by aocneanu** [comment]
You can use the actions setter in your form object and pass an array of actions.

**Comment by adithewonderboy** [comment]
Thanks for the quick reply, is there any example in Enso code that I can follow?

**Comment by adithewonderboy** [comment]
I think I have found it: 
`return $this->form->actions(['destroy', 'update'])
    ->edit($calendar); `
I was looking on the FE side all this time. 
Thanks!
